import { motion } from "motion/react";
import { ArrowLeft, Info, Cpu, FileText, Lightbulb, CheckCircle } from "lucide-react";
import { useNavigate } from "react-router";

interface SectionProps {
  icon: React.ElementType;
  title: string;
  children: React.ReactNode;
  delay?: number;
}

function Section({ icon: Icon, title, children, delay = 0 }: SectionProps) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay, duration: 0.5 }}
      className="bg-gradient-to-br from-purple-900/20 to-blue-900/20 backdrop-blur-xl border border-purple-500/30 rounded-xl p-6 hover:border-purple-500/50 transition-all"
    >
      <div className="flex items-center space-x-3 mb-4">
        <div className="w-10 h-10 rounded-lg bg-purple-500/20 flex items-center justify-center border border-purple-500/30">
          <Icon className="w-5 h-5 text-purple-400" />
        </div>
        <h2 className="text-2xl font-semibold text-white">{title}</h2>
      </div>
      <div className="text-gray-300 space-y-3">{children}</div>
    </motion.div>
  );
}

export function ContextSensitiveLanguage() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen px-4 sm:px-6 lg:px-8 py-12">
      <div className="max-w-6xl mx-auto">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-8"
        >
          <button
            onClick={() => navigate("/")}
            className="flex items-center space-x-2 text-purple-400 hover:text-purple-300 mb-6 transition-colors"
          >
            <ArrowLeft className="w-5 h-5" />
            <span>Back to Hierarchy</span>
          </button>

          <h1 className="text-5xl font-bold mb-4 bg-gradient-to-r from-purple-400 to-blue-400 bg-clip-text text-transparent">
            Context-Sensitive Languages
          </h1>
          <p className="text-gray-400 text-lg">
            More powerful than context-free, recognized by linear bounded automata
          </p>
        </motion.div>

        <div className="space-y-6">
          {/* Definition */}
          <Section icon={Info} title="Definition" delay={0.1}>
            <p>
              Context-sensitive languages are a superset of context-free languages that can express{" "}
              <span className="text-purple-400 font-semibold">context-dependent transformations</span>. They allow
              productions where the left-hand side can contain multiple symbols providing context.
            </p>
            <p>
              A language L is context-sensitive if it can be generated by a context-sensitive grammar (CSG) or
              accepted by a linear bounded automaton (LBA).
            </p>
          </Section>

          {/* Automaton Type */}
          <Section icon={Cpu} title="Automaton Type" delay={0.2}>
            <p>
              Context-sensitive languages are recognized by{" "}
              <span className="text-purple-400 font-semibold">Linear Bounded Automata (LBA)</span>:
            </p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>
                <strong className="text-white">Bounded Tape:</strong> A Turing machine with tape limited to the length
                of the input string
              </li>
              <li>
                <strong className="text-white">Read/Write Head:</strong> Can move left and right on the tape, modifying
                symbols
              </li>
              <li>
                <strong className="text-white">Space Constraint:</strong> Uses only O(n) space for input of length n
              </li>
            </ul>
            <p className="mt-3">
              The tape boundary prevents unbounded computation while allowing more complex operations than a PDA.
            </p>
          </Section>

          {/* Grammar Rules */}
          <Section icon={FileText} title="Grammar Rules" delay={0.3}>
            <p>
              Context-sensitive languages use{" "}
              <span className="text-purple-400 font-semibold">Type-1 (Context-Sensitive) Grammars</span>.
            </p>
            <p className="mt-2">Production rules have the form:</p>
            <div className="bg-black/40 rounded-lg p-4 mt-3 font-mono text-sm border border-purple-500/20">
              <div>αAβ → αγβ</div>
            </div>
            <p className="text-sm mt-2">
              where A is a non-terminal, α and β provide context, and γ is a non-empty string. The key constraint is:
              |αAβ| ≤ |αγβ| (non-contracting).
            </p>
            <div className="bg-black/40 rounded-lg p-4 mt-3 font-mono text-sm border border-purple-500/20">
              <div className="text-purple-300 mb-2">Example CSG for a^n b^n c^n:</div>
              <div>S → aSBC | aBC</div>
              <div>CB → BC</div>
              <div>aB → ab</div>
              <div>bB → bb</div>
              <div>bC → bc</div>
              <div>cC → cc</div>
            </div>
          </Section>

          {/* Example Languages */}
          <Section icon={Lightbulb} title="Example Languages" delay={0.4}>
            <div className="space-y-3">
              <div className="bg-black/40 rounded-lg p-4 border border-purple-500/20">
                <div className="text-purple-400 font-semibold mb-2">L₁ = {"{a^n b^n c^n | n ≥ 1}"}</div>
                <div className="text-sm text-gray-400">
                  Equal numbers of a's, b's, and c's in order (NOT context-free)
                </div>
              </div>
              <div className="bg-black/40 rounded-lg p-4 border border-purple-500/20">
                <div className="text-purple-400 font-semibold mb-2">L₂ = {"{ww | w ∈ {a,b}*}"}</div>
                <div className="text-sm text-gray-400">Strings consisting of two identical halves</div>
              </div>
              <div className="bg-black/40 rounded-lg p-4 border border-purple-500/20">
                <div className="text-purple-400 font-semibold mb-2">L₃ = {"{a^(2^n) | n ≥ 0}"}</div>
                <div className="text-sm text-gray-400">
                  Strings with length that is a power of 2: a, aa, aaaa, aaaaaaaa
                </div>
              </div>
            </div>
          </Section>

          {/* Visual Representation */}
          <Section icon={Cpu} title="LBA Characteristics" delay={0.5}>
            <div className="space-y-4">
              <div className="bg-black/40 rounded-lg p-6 border border-purple-500/20">
                <div className="flex items-center justify-between mb-4">
                  <div className="text-sm text-gray-400">Tape (bounded to input length)</div>
                </div>
                <div className="flex space-x-1 mb-4">
                  {["a", "b", "c", "a", "b", "c"].map((symbol, idx) => (
                    <div
                      key={idx}
                      className={`w-12 h-12 border-2 ${
                        idx === 2 ? "border-purple-500 bg-purple-500/20" : "border-blue-500/50 bg-blue-500/10"
                      } rounded flex items-center justify-center font-mono`}
                    >
                      {symbol}
                    </div>
                  ))}
                </div>
                <div className="flex items-center space-x-2 text-sm">
                  <div className="w-3 h-3 bg-purple-500 rounded-full animate-pulse" />
                  <span className="text-gray-400">Read/Write head can move and modify symbols</span>
                </div>
              </div>
              <p className="text-sm text-gray-400">
                Unlike a standard Turing machine, the LBA cannot use unlimited tape—it's restricted to the input's
                length, making it less powerful but still more capable than a PDA.
              </p>
            </div>
          </Section>

          {/* Key Properties */}
          <Section icon={CheckCircle} title="Key Properties" delay={0.6}>
            <div className="space-y-4">
              <div>
                <h3 className="text-white font-semibold mb-2">Closure Properties:</h3>
                <p className="text-sm">
                  Closed under union, intersection, concatenation, and complement. This is stronger than context-free
                  languages.
                </p>
              </div>
              <div>
                <h3 className="text-white font-semibold mb-2">Decidability:</h3>
                <p className="text-sm">
                  The membership problem for CSLs is decidable (can determine if a string belongs to the language), but
                  the emptiness problem is undecidable.
                </p>
              </div>
              <div>
                <h3 className="text-white font-semibold mb-2">Complexity:</h3>
                <p className="text-sm">
                  Context-sensitive languages correspond to the complexity class NSPACE(n), or nondeterministic linear
                  space.
                </p>
              </div>
              <div>
                <h3 className="text-white font-semibold mb-2">Applications:</h3>
                <p className="text-sm">
                  Natural language processing with contextual constraints, type systems in programming languages, and
                  protocol verification.
                </p>
              </div>
              <div>
                <h3 className="text-white font-semibold mb-2">Limitations:</h3>
                <p className="text-sm">
                  Cannot solve the Halting Problem or express all computable functions. Some decidable problems remain
                  outside this class.
                </p>
              </div>
            </div>
          </Section>
        </div>
      </div>
    </div>
  );
}
