import { motion } from "framer-motion";
import { AutomataGraph } from "../components/AutomataGraph";
import { Node, Edge } from "reactflow";
import { ArrowLeft, Info, Cpu, FileText, Lightbulb, CheckCircle } from "lucide-react";
import { useNavigate } from "react-router";

const pdaNodes: Node[] = [
  {
    id: "q0",
    type: "state",
    position: { x: 100, y: 200 },
    data: { label: "q0", isStart: true },
  },
  {
    id: "q1",
    type: "state",
    position: { x: 400, y: 200 },
    data: { label: "q1" },
  },
  {
    id: "q2",
    type: "state",
    position: { x: 700, y: 200 },
    data: { label: "q2", isAccept: true },
  },
];

const pdaEdges: Edge[] = [
  {
    id: "q0-q1",
    source: "q0",
    target: "q1",
    label: "ε, ε → $",
    type: "straight",
    style: {
      stroke: "#a855f7",
      strokeWidth: 5,
    },
    labelStyle: {
      fill: "#ffffff",
      fontSize: "14px",
      fontWeight: 600,
    },
    labelBgStyle: {
      fill: "#1f1f2e",
      stroke: "#a855f7",
      strokeWidth: 1,
    },
    labelBgPadding: [10, 6],
    labelBgBorderRadius: 6,
    markerEnd: {
      type: "arrowclosed",
      color: "#a855f7",
      width: 25,
      height: 25,
    },
  },

  {
    id: "q1-q2",
    source: "q1",
    target: "q2",
    label: "ε, $ → ε",
    type: "straight",
    style: {
      stroke: "#a855f7",
      strokeWidth: 5,
    },
    labelStyle: {
      fill: "#ffffff",
      fontSize: "14px",
      fontWeight: 600,
    },
    labelBgStyle: {
      fill: "#1f1f2e",
      stroke: "#a855f7",
      strokeWidth: 1,
    },
    labelBgPadding: [10, 6],
    labelBgBorderRadius: 6,
    markerEnd: {
      type: "arrowclosed",
      color: "#a855f7",
      width: 25,
      height: 25,
    },
  },
];

interface SectionProps {
  icon: React.ElementType;
  title: string;
  children: React.ReactNode;
  delay?: number;
}

function Section({ icon: Icon, title, children, delay = 0 }: SectionProps) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay, duration: 0.5 }}
      className="bg-gradient-to-br from-purple-900/20 to-blue-900/20 backdrop-blur-xl border border-purple-500/30 rounded-xl p-6 hover:border-purple-500/50 transition-all"
    >
      <div className="flex items-center space-x-3 mb-4">
        <div className="w-10 h-10 rounded-lg bg-purple-500/20 flex items-center justify-center border border-purple-500/30">
          <Icon className="w-5 h-5 text-purple-400" />
        </div>
        <h2 className="text-2xl font-semibold text-white">{title}</h2>
      </div>
      <div className="text-gray-300 space-y-3">{children}</div>
    </motion.div>
  );
}

export function ContextFreeLanguage() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen px-4 sm:px-6 lg:px-8 py-12">
      <div className="max-w-6xl mx-auto">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-8"
        >
          <button
            onClick={() => navigate("/")}
            className="flex items-center space-x-2 text-purple-400 hover:text-purple-300 mb-6 transition-colors"
          >
            <ArrowLeft className="w-5 h-5" />
            <span>Back to Hierarchy</span>
          </button>

          <h1 className="text-5xl font-bold mb-4 bg-gradient-to-r from-purple-400 to-blue-400 bg-clip-text text-transparent">
            Context-Free Languages
          </h1>
          <p className="text-gray-400 text-lg">
            Languages with nested structures, recognized by pushdown automata
          </p>
        </motion.div>

        <div className="space-y-6">
          {/* Definition */}
          <Section icon={Info} title="Definition" delay={0.1}>
            <p>
              Context-free languages are a superset of regular languages that can express{" "}
              <span className="text-purple-400 font-semibold">recursive and nested structures</span>. They require a
              stack memory to recognize patterns like balanced parentheses or matching symbols.
            </p>
            <p>
              A language L is context-free if it can be generated by a context-free grammar (CFG) or accepted by a
              pushdown automaton (PDA).
            </p>
          </Section>

          {/* Automaton Type */}
          <Section icon={Cpu} title="Automaton Type" delay={0.2}>
            <p>
              Context-free languages are recognized by{" "}
              <span className="text-purple-400 font-semibold">Pushdown Automata (PDA)</span>:
            </p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>
                <strong className="text-white">Stack Memory:</strong> PDAs have an infinite stack that can store and
                retrieve symbols
              </li>
              <li>
                <strong className="text-white">Enhanced Power:</strong> The stack allows counting and matching of
                symbols across arbitrary distances
              </li>
              <li>
                <strong className="text-white">Nondeterministic:</strong> Most CFLs require nondeterministic PDAs
              </li>
            </ul>
          </Section>

          {/* Grammar Rules */}
          <Section icon={FileText} title="Grammar Rules" delay={0.3}>
            <p>
              Context-free languages use <span className="text-purple-400 font-semibold">Type-2 (Context-Free) Grammars</span>.
            </p>
            <p className="mt-2">Production rules have the form:</p>
            <div className="bg-black/40 rounded-lg p-4 mt-3 font-mono text-sm border border-purple-500/20">
              <div>A → α</div>
            </div>
            <p className="text-sm mt-2">
              where A is a single non-terminal and α is any string of terminals and non-terminals.
            </p>
            <div className="bg-black/40 rounded-lg p-4 mt-3 font-mono text-sm border border-purple-500/20">
              <div className="text-purple-300 mb-2">Example CFG for a^n b^n:</div>
              <div>S → aSb | ε</div>
            </div>
          </Section>

          {/* Example Languages */}
          <Section icon={Lightbulb} title="Example Languages" delay={0.4}>
            <div className="space-y-3">
              <div className="bg-black/40 rounded-lg p-4 border border-purple-500/20">
                <div className="text-purple-400 font-semibold mb-2">L₁ = {"{a^n b^n | n ≥ 0}"}</div>
                <div className="text-sm text-gray-400">Equal number of a's followed by equal b's</div>
              </div>
              <div className="bg-black/40 rounded-lg p-4 border border-purple-500/20">
                <div className="text-purple-400 font-semibold mb-2">L₂ = Balanced Parentheses</div>
                <div className="text-sm text-gray-400">All strings with properly nested parentheses: (), (()), (()())</div>
              </div>
              <div className="bg-black/40 rounded-lg p-4 border border-purple-500/20">
                <div className="text-purple-400 font-semibold mb-2">L₃ = Palindromes</div>
                <div className="text-sm text-gray-400">Strings that read the same forwards and backwards: aba, abba, etc.</div>
              </div>
            </div>
          </Section>

          {/* Visual Automaton */}
          <Section icon={Cpu} title="Example PDA" delay={0.5}>
            <p className="mb-4">
              Below is a simplified PDA representation for recognizing a^n b^n:
            </p>
            <AutomataGraph nodes={pdaNodes} edges={pdaEdges} />
            <div className="mt-4 text-sm space-y-2">
              <p className="text-gray-400">
                <strong className="text-white">How it works:</strong> Push 'a' symbols onto the stack, then pop for each 'b'. Accept if stack is empty at the end.
              </p>
            </div>
          </Section>

          {/* Key Properties */}
          <Section icon={CheckCircle} title="Key Properties" delay={0.6}>
            <div className="space-y-4">
              <div>
                <h3 className="text-white font-semibold mb-2">Closure Properties:</h3>
                <p className="text-sm">
                  Closed under union, concatenation, and Kleene star. <strong>NOT closed</strong> under intersection
                  or complementation.
                </p>
              </div>
              <div>
                <h3 className="text-white font-semibold mb-2">Pumping Lemma for CFLs:</h3>
                <p className="text-sm">
                  If L is context-free, then for any sufficiently long string s, it can be divided into uvxyz such
                  that uv^i xy^i z ∈ L for all i ≥ 0.
                </p>
              </div>
              <div>
                <h3 className="text-white font-semibold mb-2">Applications:</h3>
                <p className="text-sm">
                  Programming language syntax, XML/HTML parsing, arithmetic expressions, and natural language processing.
                </p>
              </div>
              <div>
                <h3 className="text-white font-semibold mb-2">Limitations:</h3>
                <p className="text-sm">
                  Cannot express languages like {"{a^n b^n c^n | n ≥ 0}"} which require counting multiple dependencies
                  simultaneously.
                </p>
              </div>
            </div>
          </Section>
        </div>
      </div>
    </div>
  );
}
