questions = [
    {"id": 1, "language": "L = { a^n b^n | n ≥ 0 }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Context Free"},
    {"id": 2, "language": "L = (a+b)*", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Regular"},
    {"id": 3, "language": "L = { a^n b^n c^n | n ≥ 1 }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Context Sensitive"},
    {"id": 4, "language": "L = { ww | w ∈ {a,b}* }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Context Sensitive"},
    {"id": 5, "language": "L = { a^n b^m | n,m ≥ 0 }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Regular"},
    {"id": 6, "language": "L = { a^n b^n c^m | n,m ≥ 0 }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Context Free"},
    {"id": 7, "language": "L = { (ab)^n | n ≥ 0 }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Regular"},
    {"id": 8, "language": "L = { a^p | p is prime }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Context Sensitive"},
    {"id": 9, "language": "L = { a^n b^n c^n d^n | n ≥ 1 }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Context Sensitive"},
    {"id": 10, "language": "L = { a^i b^j c^k | i=j or j=k }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Context Free"},
    {"id": 11, "language": "L = { w | w contains substring 'aba' }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Regular"},
    {"id": 12, "language": "L = { w | w is a palindrome over {a,b} }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Context Free"},
    {"id": 13, "language": "L = { w w^R | w ∈ {0,1}* }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Context Free"},
    {"id": 14, "language": "L = { a^n b^2n | n ≥ 1 }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Context Free"},
    {"id": 15, "language": "L = { a^m b^n | m ≠ n }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Context Free"},
    {"id": 16, "language": "L = { a^(n^2) | n ≥ 1 }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Context Sensitive"},
    {"id": 17, "language": "L = { a^n | n is even }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Regular"},
    {"id": 18, "language": "L = { a^n b^m c^l | n+m=l }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Context Free"},
    {"id": 19, "language": "L = { a^n b^m c^k | n=m=k }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Context Sensitive"},
    {"id": 20, "language": "L = { a^n b^m | n > m }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Context Free"},
    {"id": 21, "language": "L = { a^n b^n | n is a power of 2 }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Context Sensitive"},
    {"id": 22, "language": "L = { w | w has equal number of a's and b's }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Context Free"},
    {"id": 23, "language": "L = { a^n b^j a^n | n,j ≥ 1 }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Context Free"},
    {"id": 24, "language": "L = { a^n b^m a^k | n=m+k }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Context Free"},
    {"id": 25, "language": "L = { a^n b^m | n=2m }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Context Free"},
    {"id": 26, "language": "L = { a^n b^n a^n b^n | n ≥ 1 }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Context Sensitive"},
    {"id": 27, "language": "L = { a^i b^j | i,j ≥ 0 and i+j is even }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Regular"},
    {"id": 28, "language": "L = { a^n b^m | n,m ≥ 1, gcd(n,m)=1 }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Recursively Enumerable"},
    {"id": 29, "language": "L = { w | w starts and ends with same symbol }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Regular"},
    {"id": 30, "language": "L = { a^n b^m | n ≥ m ≥ 0 }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Context Free"},
    {"id": 31, "language": "L = { a^n b^n c^n d^n e^n | n ≥ 1 }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Context Sensitive"},
    {"id": 32, "language": "L = { a^n b^m c^n b^m | n,m ≥ 1 }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Context Sensitive"},
    {"id": 33, "language": "L = { a^n | n is a perfect square }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Context Sensitive"},
    {"id": 34, "language": "L = { w | w has no three consecutive a's }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Regular"},
    {"id": 35, "language": "L = { a^n b^m | n ≤ m ≤ 2n }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Context Free"},
    {"id": 36, "language": "L = { a^n b^n c^i | n ≤ i }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Context Sensitive"},
    {"id": 37, "language": "L = { w | length of w is a multiple of 3 }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Regular"},
    {"id": 38, "language": "L = { a^n b^m | n! = m }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Context Sensitive"},
    {"id": 39, "language": "L = { a^i b^j c^k | i < j < k }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Context Sensitive"},
    {"id": 40, "language": "L = { w c w | w ∈ {a,b}* }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Context Sensitive"},
    {"id": 41, "language": "L = { a^n b^m | n,m > 0 }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Regular"},
    {"id": 42, "language": "L = { a^n b^n | n is not prime }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Context Free"},
    {"id": 43, "language": "L = { a^i b^j c^k | i=j and j=k }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Context Sensitive"},
    {"id": 44, "language": "L = { w | w contains even number of 0's }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Regular"},
    {"id": 45, "language": "L = { a^n b^k c^n | n,k ≥ 0 }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Context Free"},
    {"id": 46, "language": "L = { a^i b^j | i ≥ 1, j ≥ 1 }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Regular"},
    {"id": 47, "language": "L = { w | w is a valid C program }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Context Sensitive"},
    {"id": 48, "language": "L = { <M> | M is a TM that halts on empty input }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Recursively Enumerable"},
    {"id": 49, "language": "L = { a^n b^n | n ≤ 100 }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Regular"},
    {"id": 50, "language": "L = { a^n b^m c^k | i+j=k }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Context Free"},
    {"id": 51, "language": "L = { a^n b^n c^n | n is constant }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Regular"},
    {"id": 52, "language": "L = { w | w has more a's than b's }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Context Free"},
    {"id": 53, "language": "L = { a^n b^m a^n b^m | n,m ≥ 0 }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Context Sensitive"},
    {"id": 54, "language": "L = { w | w is a binary representation of a prime }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Context Sensitive"},
    {"id": 55, "language": "L = { ε }", "options": ["Regular", "Context Free", "Context Sensitive", "Recursively Enumerable"], "correct": "Regular"}
]